[project]
name = 'smart-contracts'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.basic-utils]
path = 'contracts/basic-utils.clar'
clarity_version = 2
epoch = 2.4

[contracts.channel-shareholders]
path = 'contracts/channel-shareholders.clar'
clarity_version = 2
epoch = 2.4

[contracts.channel-shares]
path = 'contracts/channel-shares.clar'
clarity_version = 2
epoch = 2.4

[contracts.contract]
path = 'contracts/contract.clar'
clarity_version = 2
epoch = 2.4

[contracts.contractv2]
path = 'contracts/contractv2.clar'
clarity_version = 2
epoch = 2.4

[contracts.shareholders]
path = 'contracts/shareholders.clar'
clarity_version = 2
epoch = 2.4

[contracts.video-nft]
path = 'contracts/video-nft.clar'
clarity_version = 2
epoch = 2.4

[contracts.video-nfts]
path = 'contracts/video-nfts.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
